function H1err = getH1Error(out,gradSol)
% getH1Error computes the H1 seminorm error for the numerical solution of Poisson
% problem
%
% SYNOPSIS: H1err = getH1Error(out,gradSol)
%
% INPUT: out: structure generated by vem2d.m with the numerical solution
%	     gradSol: function handle with the gradient of the exact solution
%
% OUTPUT: H1err: numerical approximation for the H1 seminorm error

proj  = out.proj;  
u     = out.u;
mesh  = out.mesh;  
polys = out.polys;

H1err = 0;

for E = 1:size(mesh.elems,1)

    verts = mesh.verts(mesh.elems{E},:);
    [h,~,xb] = geomElement(verts);

    tri  = delaunay(verts(:,1),verts(:,2));
    coef = proj{E}*u(mesh.dof{E});

    valE = 0;

    for k = 1:size(tri,1)

        xx = verts(tri(k,:),:);

        B11 = xx(2,1)-xx(1,1);
        B12 = xx(3,1)-xx(1,1);
        B21 = xx(2,2)-xx(1,2);
        B22 = xx(3,2)-xx(1,2);

        detB = abs(B11*B22-B12*B21);

        x = @(xh,yh) B11*xh+B12*yh+xx(1,1);
        y = @(xh,yh) B21*xh+B22*yh+xx(1,2);

        fun = @(xh,yh) computeGradErrorSq( ...
            x(xh,yh), y(xh,yh), coef, polys, xb, h, gradSol);

        valE = valE + detB * integral2(fun,0,1,0,@(x)1-x);
    end

    H1err = H1err + valE;
end

H1err = sqrt(H1err);
end

function res = computeGradErrorSq(x,y,coef,polys,xb,h,gradSol)
    [duhx, duhy] = evalProjGrad(x,y,coef,polys,xb,h);
    [gx, gy] = gradSol(x,y);
    res = (gx - duhx).^2 + (gy - duhy).^2;
end

function [dux, duy] = evalProjGrad(x,y,coef,polys,xb,h)
    dux = 0; duy = 0;
    for i = 1:size(polys,1)
        px = polys(i,1); py = polys(i,2);
        if px > 0
            dux = dux + coef(i) * (px/h) * ((x-xb(1))/h).^(px-1) .* ((y-xb(2))/h).^py;
        end
        if py > 0
            duy = duy + coef(i) * (py/h) * ((x-xb(1))/h).^px .* ((y-xb(2))/h).^(py-1);
        end
    end
end